# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d3ec8dd21abaebc4c986021aa2d31d5e82b7f952817010d52088a3f432b676ac1675b53aed751ed70192f67c855b1f34aa559ee28d446b738224ddba32c91081

test:
  secret_key_base: d323a0b217bcfb4bdf661fce4ed7202bacddbb73ead5d86455b4c53e77277645a1865de2a9a6ed137ffd87b2d473a3652215c077d715db0a920dd7302fec2dfa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
